FROM node:18.18.2-alpine3.18

WORKDIR /home/web-server

COPY web-server/docker/package.json /home/web-server/
COPY web-server/.output/ /home/web-server/.output/

RUN npm set registry https://registry.npmjs.org
RUN npm install

ENV NODE_ENV=production

EXPOSE 3000

CMD [ "npm", "run", "preview" ]