FROM node:18.18.2-alpine3.18

WORKDIR /home/web-server

COPY web-server/package.json /home/web-server/
COPY web-server/.eslintrc /home/web-server/
COPY web-server/.npmrc /home/web-server/
COPY web-server/tsconfig.json /home/web-server/
COPY web-server/uno.config.ts /home/web-server/

RUN npm install -g pnpm
RUN pnpm install

VOLUME "/home/web-server/src"
VOLUME "/home/web-server/.nuxt"
VOLUME "/home/web-server/nuxt.config.ts"

ENV NODE_ENV=development

EXPOSE 3000

CMD [ "npm", "run", "dev" ]