---
# 视图
views: 
  - name: find_user
    component: FormWrap
    options:
      size: large
      inline: true
      columns:
        - key: create_at
          label: 注册时间
          type: datetimerange
          placeholder: [ 选择开始时间, 选择结束时间 ]
          options:
            clearable: true
        - key: findname
          label: 查询名称
          type: text
          placeholder: 请输入查询名称
          labelWidth: 120px
          labelOptions:
            key: findtype
            data:
              - value: username
                label: 用户名
              - value: nickname
                label: 昵称
              - value: email
                label: 电子邮箱
              - value: mobilb
                label: 手机号
          options:
            clearable: true
          width: 300
        - key: group
          label: 用户组
          type: select
          placeholder: 请输选择用户组
          data:
            method: POST
            url: /api/uc/group
          props:
            value: _id
            label: name
          format: '[{id}] {label}'
          options:
            multiple: true
            collapseTags: true
      defaultValues: |-
        findtype: username
      options:
        assokey: t3921
        assignment:
          data: data.data
          counts: data.counts
          pagination: data.limit
        pageInfo:
          page: 1
          size: 10
        reset: 重置
        emits:
          - key: dialog1
            type: button
            name: 创建用户
            style: success
            command: dialog:create_user
          - key: deletes
            type: button
            name: 删除选中
            style: danger
            disabled: |-
              cache.t3921.selection:
                $size: 0
            command: action:deletes
      submitName: 查 询
      action:
        method: POST
        url: /api/uc/user

  - name: table_user
    component: Table
    options:
      assokey: t3921
      selection:
        open: true
        disabled: |-
          row.group.level:
            $gte: {{user.group.level}}
      columns:
        - key: id
          label: ID
          width: 60
        - key: username
          label: 用户名
          width: 120
          sortable: true
        - key: nickname
          label: 昵称
          width: 120
          align: left
          defaultValue: --
        - key: sex
          label: 性别
          width: 90
          format:
            - type: number
              maps: { 0: 未知, 1: 男, 2: 女 }
        - key: group
          label: 用户组
          width: 180
          format:
            - type: map
              maps: name
        - key: email
          label: 电子邮箱
          width: 240
          align: left
          format:
            - type: string
              regexp: \w{4}@
              substr: '****@'
          defaultValue: --
        - key: mobile
          label: 手机号
          width: 120
          align: left
          format:
            - type: string
              regexp: ^(\d{3})\d+(\d{4})$
              substr: '$1****$2'
          defaultValue: --
        - key: create_at
          label: 创建时间
          width: 180
          align: left
          format:
            - type: date
              func: dateFormat
              options: [ 'YYYY-MM-DD HH:mm:ss' ]
          sortable: true
        - key: $space
          minWidth: 10 
        - key: actions
          label: 操作
          fixed: right
          align: left
          width: 240
          emits:
            - key: edit
              type: button
              name: 编辑
              disabled: |-
                row.group.level:
                  $gte: {{user.group.level}}
                row._id: 
                  $not: {{user._id}}
              command: dialog:edit_user
            - key: remove
              type: button
              style: danger
              name: 删除
              disabled: |-
                row.group.level:
                  $gte: {{user.group.level}}
              command: action:remove_user



  - name: 'dialog:create_user'
    component: DialogForm
    options: 
      title: 创建用户
      closeOnClickModal: false
      closeOnPressEscape: true
      size: large
      labelWidth: 150
      asteriskPosition: right
      width: 800
      height: 450
      inlineMessage: true
      columns:
        - key: username
          label: 用户名
          type: text
          width: 300
          placeholder: 请填写用户名
        - key: password
          label: 登录密码
          type: password
          width: 300
          placeholder: 请填写登录密码
        - key: group
          label: 用户组
          type: select
          placeholder: 请输选择用户组
          data:
            method: POST
            url: /api/uc/group/list
          props:
            value: _id
            label: name
          format: '[{id}] {label}'
        - key: nickname
          label: 昵称
          type: text
          width: 300
          placeholder: 请输入昵称
        - key: sex
          label: 性别
          type: radio
          data:
            - value: '0'
              label: 未知
            - value: '1'
              label: 男
            - value: '2'
              label: 女
        - key: email
          label: 电子邮箱
          type: text
          width: 300
          placeholder: 请输入电子邮箱
        - key: mobile
          label: 手机号码
          type: text
          width: 300
          placeholder: 请输入手机号码
        - key: binds
          label: 绑定
          type: checkbox
          data:
            - value: email
              label: 电子邮箱
            - value: mobile
              label: 手机号码
      defaultValues: |-
        sex: '0'
      verifyRules:
        username: 
          - required: true
            message: 请填写用户名
          - validator: [validateUsername, username, null]
            trigger: [blur, change]
        password:
          - required: true
            message: 请填写登录密码
          - validator: [validatePassword]
            trigger: [blur, change]
        group:
          - required: true
            message: 请选择用户组
        email:
          - validator: [validateEmail, email, null]
            trigger: [blur, change]
        mobile:
          - validator: [validateMobile, zh-CN, mobile, null]
            trigger: [blur, change]
      uniqueOptions:
        data: |-
          name: '{{name}}'
      options:
        hide: true
        afterCommand:
          - action:refresh
      action:
        method: POST
        url: /api/uc/user/create


  - name: 'dialog:edit_user'
    component: DialogForm
    options: 
      title: 编辑用户
      closeOnClickModal: false
      closeOnPressEscape: true
      size: large
      labelWidth: 150
      asteriskPosition: right
      width: 800
      height: 450
      inlineMessage: true
      columns:
        - key: username
          label: 用户名
          type: text
          width: 300
          placeholder: 请填写用户名
        - key: password
          label: 登录密码
          type: password
          width: 300
          placeholder: 不修改请不要填写
        - key: group
          label: 用户组
          type: select
          placeholder: 请输选择用户组
          data:
            method: POST
            url: /api/uc/group/list
          props:
            value: _id
            label: name
          format: '[{id}] {label}'
          disabled: |-
            dialog.edit_user.row.group.level: 9999
          conditions: |-
            dialog.edit_user.row.group.level:
              $lt: 9999
        - key: nickname
          label: 昵称
          type: text
          width: 300
          placeholder: 请输入昵称
        - key: sex
          label: 性别
          type: radio
          data:
            - value: '0'
              label: 未知
            - value: '1'
              label: 男
            - value: '2'
              label: 女
        - key: email
          label: 电子邮箱
          type: text
          width: 300
          placeholder: 请输入电子邮箱
        - key: mobile
          label: 手机号码
          type: text
          width: 300
          placeholder: 请输入手机号码
        - key: binds
          label: 绑定
          type: checkbox
          data:
            - value: email
              label: 电子邮箱
            - value: mobile
              label: 手机号码
      defaultValues: |-
        username: '{{dialog.edit_user.row.username}}'
        group: '{{dialog.edit_user.row.group._id}}'
        nickname: '{{dialog.edit_user.row.nickname}}'
        sex: '{{dialog.edit_user.row.sex}}'
        email: '{{dialog.edit_user.row.email}}'
        mobile: '{{dialog.edit_user.row.mobile}}'
        binds: [{% for item in dialog.edit_user.row.binds %} {{item}}, {% endfor %}]
      verifyRules:
        username: 
          - required: true
            message: 请填写用户名
          - validator: [validateUsername, username, null]
            trigger: [blur, change]
        password:
          - validator: [validatePassword]
            trigger: [blur, change]
        email:
          - validator: [validateEmail, email, null]
            trigger: [blur, change]
        mobile:
          - validator: [validateMobile, zh-CN, mobile, null]
            trigger: [blur, change]
      uniqueOptions:
        data: |-
          name: '{{name}}'
          uid: '{{dialog.edit_user.row._id}}'
      options:
        hide: true
        changeSubmit: true
        afterCommand:
          - action:refresh
      action:
        method: POST
        url: /api/uc/user/edit/{{dialog.edit_user.row._id}}
