version: '3.7'

services:
  api_server:
    image: playground_api_server:dev
    container_name: playground_api-server
    build: 
      context: .
      dockerfile: ./api-server/Dockerfile.dev
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      - SITE_NAME=${SITE_NAME}
      - SITE_URL=${SITE_URL}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGODB_HOST=${MONGODB_HOST:-mongodb}
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - SERVER_NAME=${SERVER_NAME}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASS=${REDIS_PASS}
      - ADMIN_NAME=${ADMIN_NAME:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin888}
    volumes:
      - ${PWD}/api-server/config:/usr/src/app/config
      - ${PWD}/api-server/channels:/usr/src/app/channels
      - ${PWD}/api-server/logs:/usr/src/app/logs
      - ${PWD}/api-server/mails:/usr/src/app/mails
      - ${PWD}/api-server/static:/usr/src/app/static
      - ${PWD}/api-server/uploadfiles:/usr/src/app/uploadfiles
      - ${PWD}/api-server/views:/usr/src/app/views
      - ${PWD}/api-server/src:/usr/src/app/src
      - ${PWD}/api-server/dist:/usr/src/app/dist
    ports:
      - ${API_SERVER_PORT:-4000}:4000

  web-server:
    image: playground_web_server:dev
    container_name: playground_web-server
    build: 
      context: .
      dockerfile: ./web-server/Dockerfile.dev
    restart: always
    environment:
      - NUXT_PUBLIC_API_BASE=${API_BASEURL}
    volumes:
      - ${PWD}/web-server/src:/home/web-server/src
      - ${PWD}/web-server/.nuxt:/home/web-server/.nuxt
      - ${PWD}/web-server/nuxt.config.ts:/home/web-server/nuxt.config.ts
    ports:
      - ${WEB_SERVER_PORT:-3000}:3000
      - 24678:24678

  mongodb: 
    image: mongo:4.4.22-focal
    container_name: playground_mongodb
    restart: always

  redis:
    image: redis:6.2.12-alpine3.18
    container_name: playground_redis
    restart: always
    command: redis-server
