---
name: register

payload:
  - key: username
    type: string
    rules:
      - required: true
        message: 账户名不能为空
        code: 1000
      - pattern: !!js/regexp /^[a-zA-Z]{1}[a-zA-Z0-9\_\-]/
        message: 账户名必须英文字符开头，可包含英文字符、数字、下划线及中划线
        code: 1000
      - min: 5
        max: 20
        message: 长度限定 5 - 20 位字符
        code: 1000
  - key: email
    type: string
    rules:
      - required: true
        message: 电子邮箱不能为空
        code: 1000
      - validator: isEmail
        message: 请输入正确的邮箱地址，如 example@163.com
        code: 1000
  - key: password
    type: string
    rules:
      - required: true
        message: 密码不能为空
        code: 1000
      - pattern: !!js/regexp /^(?=.*[A-Za-z])[A-Za-z0-9$@$!%*#?&]/
        message: 密码字段必须包含英文字符，可包含英文字符、数字和符号
        code: 1000
      - min: 8
        max: 20
        message: 密码长度限定 8 - 20 位字符
        code: 1000
