---
name: 默认策略

# 频道策略
channels: []
      

# API策略
apis:
  - path: /api/uc/account/login
    method: [ post ]
  - path: /api/uc/account/refresh_token
    method: [ put ]
  - path: /api/uc/account/verify
    method: [ put ]
  - path: /api/uc/account/register
    method: [ post ]

