---
key: 01.account
name: 账户中心
route: /account
children:
  - name: 账户管理
    children:
      - name: 基本资料
        route: /baseinfo
      - name: 安全设置
        route: /security
      - name: 站内消息
        route: /notification