---
name: list

auth: 9998

payload:
  - key: name
    type: string
  - key: type
    type: string
  - key: usage
    type: string
    rules:
      - pattern: !!js/regexp /^(true|false)$/
        message: 使用状态必须是个 Boolean 值
        code: 1000
    format:
      - type: map
  - key: expired
    type: string
    rules:
      - pattern: !!js/regexp /^(true|false)$/
        message: 过期状态必须是个 Boolean 值
        code: 1000
    format:
      - type: map
  - key: page
    type: number
    defaultValue: 1
  - key: size
    type: number
    defaultValue: 10
  - key: sort
    type: string[]