---

default:
  name: 默认
  description: 默认存储器
  max_limit: 4mb
  mime_types:
    - image/png
    - image/jpeg
    - image/webp
  root_dir: uploadfiles/files
  urlprefix: /uploadfiles/files

avatar:
  name: 头像
  description: 用户头像
  max_limit: 4mb
  mime_types:
    - image/png
    - image/jpeg
    - image/webp
  root_dir: uploadfiles/avatar
  urlprefix: /uploadfiles/avatar
  original_name: true
  userDir: true