---
# Action 请求
actions:
  plot_list:
    request:
      method: GET
      url: /api/uc/plot/list
    options:
      assokey: parse
      assignment:
        plots: data
  refresh:
    request:
      method: POST
      url: /api/uc/group
    options:
      assokey: t1
      refresh: true
      assignment:
        data: data
  remove_group:
    request:
      method: DELETE
      url: /api/uc/group/{{row._id}}
    options:
      afterCommand:
        - action:refresh
    confirm:
      message: 确认要删除该用户组, 是否继续?
      cancel: 您已取消删除操作！

# 初始化数据
initial:
  - action:plot_list
  - action:refresh