---
name: edit

auth: 9998

payload:
  - key: name
    type: string
    rules:
      - required: true
        message: 用户组名称不能为空
        code: 1000
  - key: level
    type: number
  - key: description
    type: string